# Generated by Django 4.0.3 on 2022-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='productid',
        ),
        migrations.AddField(
            model_name='cart',
            name='no',
            field=models.DecimalField(decimal_places=0, default='SOME INTEGER', max_digits=11),
        ),
        migrations.AddField(
            model_name='cart',
            name='prod',
            field=models.DecimalField(decimal_places=0, default='SOME INTEGER', max_digits=11),
        ),
    ]
